apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/smeelock/training-argocd
    targetRevision: HEAD
    path: ./apps/argocd
  destination:
    name: in-cluster
    namespace: argocd