apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  namespace: demo
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/smeelock/training-argocd
    targetRevision: HEAD
    path: ./apps/demo
    helm:
      valueFiles:
        - values.yaml
  destination:
    name: in-cluster
    namespace: demo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
